### ISSUE TITLE
Code hangs in setup

### ISSUE THREAD

**Issue by Gavin-Perry** [MrYsLab/NeoPixelConnect#2] opened 2022-03-19 21:51 UTC
Thanks for the nice implementation of WS28xx on the PICO
When used alone on RP2040-Zero (Generic) NeopixelConnect works fine.
I am using it for the single WS2812 built onto the board at GPIO 16
When I put it into my program it hangs in setup  the second time I call.
Just realized that is after I've called my PIO setup.
The problem was I don't know what value is given for pixelPIO (which PIO is use)
Much digging and I find it defined in the .h file as PIO0 
It would be really nice if pixelPIO was one of the passed parameters in the instantiation.
Also is it possible to make it not crash if the PIO is  changed?
I'll use PIO1 for my stuff for now.
Also naming the library NeoPixel4Pico or some such would make it clearer and easier to find.

**Comment by MrYsLab** [comment] 2022-03-19 23:18
@Gavin-Perry Thanks for the suggestion. This library was intended to be used with the Arduino Nano RP2040 Connect, thus the name. In fact, the title in README.md is **WS2812 NeoPixel Library For the Arduino Nano RP2040 Connect.** 

Still, your request is a valid one.

I understand the request to make the PIO selectable, but I don't understand the following statement above:

>  Also, is it possible to make it not crash if the PIO is changed?

Are you saying that the code would crash if the PIO and SM are changed to something other than pio0 and sm0?

I am working on other projects at the moment, so I am not sure when I would get to implement the suggested enhancement. However, I will leave this issue open until I have the time to implement it.

**Comment by Gavin-Perry** [comment] 2022-03-19 23:30
What I am saying is if after calling NeopixelConnect I call my instance of DMX and step on yours then how can I know this? the hang at the next call took a long time to figure out.
You have a fantastic implementation of the basic WS28xx code for all RP-PICO don't be shy, not just Connect.
Not much more needed to do everything FastLED does. Maybe he can just incorporate your brilliant code to make FastLED work on Pico?

**Comment by MrYsLab** [comment] 2022-03-19 23:47
So if I understand you correctly, there is a conflict between this library and the DMX library you are using. By allowing you to select the pio and sm, the conflict can be manually resolved, and no more crashes. However, one still needs to know if another library uses the PIO SM pair. 

You give me too much credit ;-). All I did was package the Raspberry Pi folks' example into a package that the Arduino Library manager can support.

If the author of FastLED wishes to incorporate this library, I have no objections. If that solves the issue quicker than I can get around to it, by all means, go for it ;-).

**Comment by Gavin-Perry** [comment] 2022-03-20 04:27
You are correct. I spent far too long chasing down the conflict. Any library that uses pio should let you pick which one since it is a very powerful piece of hardware that can be used by multiple libraries. I guess one could also document how much of the pio is used since apparently it can be shared by multiple instances if not multiple libraries. The DMX library says you can put in three instances. I'm guessing yours use more than 2/3.

**Comment by MrYsLab** [comment] 2022-03-20 15:02
Each of the four state machines can be associated with either pio0 or pio1. The four state machines share the same PIO memory. That memory can hold up to 32 PIO instructions. This library uses four PIO instructions, as can be seen [here](https://github.com/MrYsLab/NeoPixelConnect/blob/30126903424c8f5f4b6b6e6b3ddc8e1857164f9c/src/ws2812.pio.h#L20). 

One can place PIO code for more than one application in the same file. [Here](https://github.com/MrYsLab/Telemetrix4RpiPico/blob/master/Telemetrix4RpiPico.pio) the PIO code handles both the HC-SR04 and NexPixels.

The PIO, although simple in concept, it is actually quite complicated. There is an excellent [short YouTube tutorial](https://www.youtube.com/watch?v=yYnQYF_Xa8g) available if you are interested.

I do not know if the compiler errors out if the combined number of PIO instructions exceeds 32 PIO instructions. For better or worse, a PIO user is forced to understand some of the lower-level details of PIO programming and make sure that their application is within the limitations of PIO programming. A PIO library can only be responsible for itself. It is up to the application developer to ensure that the combined PIO code is within bounds.

**Comment by Gavin-Perry** [comment] 2022-03-21 02:48
Thank you for your help.

As a firmware programmer that started with 6502, probably before you were
born, I do understand how PIO works.
About a decade ago I was busy programming FPGAs. I've also been doing lots
or projects in the last few years with WS28xx
both RGB and RGBW as well as AP102 (DotStar) for faster updating (POV apps).

I have to admit however, that I was not planning to be programming the PIO
myself which is why I turned to your library to do the dirty work. When you
release libraries to Arduino space you can expect a lot of users who have
no idea what they are doing and will not understand even the concept of a
PIO. That is why IMHO the library author should well document the usage of
the library and what it's requirements will be. I.e.
*Uses 4 PIO instructions, defaulting to PIO0. This can be changed here
______*

Meanwhile, I have another request. I wanted to be able to add a color to an
already on pixel. e.g. Turn a red to purple by adding blue.
FOr that to work I would need access to pixelBuffer[num][clr].  I tried
moving it out of the private space and then using extern ... in my .INO
file to no avail. I'm just not that familiar with how Arduino handles
libraries.
I ended up with a very crude local copy of the data not even using arrays
at all since what I need for this app is so simple.

Minimal code
NeoPixelConnect iLED(LED_PIN, 1);
...
iLED.neoPixelFill(0, 10 , 0, true);  // green (not too bright)
delay(HowLong);
iLED.neoPixelFill(32, 15, 0, true);  // Yellow
delay(HowLong);
} // End Loop

ISSUE
It appears that the routine  neoPixelFill() even with only 1 LED takes a
long time to finish the internal work
If HowLong is too short (on the order of 50-100msec) updates don't happen.

I thought I was testing high numbered input pins that seemed to not be
working (see attached) but it turned out that the pixel wasn't
updating.consistently. It would stay off even though serial monitor data
was working fine.
Maybe you can test it on your hardware and get different results?
SHorten the delays until it fails.


TODO
 Is it possible to make the buffer externally accessible?
 OR (better yet) write a routine that reads back the contents of the array
 AND more routines for e.g. adding color, setting background color
Well at this point I guess handing it over to Marc Miller @marmilicious at
FastLED
https://fastled.io/docs/3.1/md__p_o_r_t_i_n_g.html

Thanks again for getting me started with the WS2812 on my RP2040


--
Gavin

**Comment by MrYsLab** [comment] 2022-03-21 14:26
I will update the documentation when I modify the code. However, even with your suggested doc changes, the user still needs to understand why they should care how many PIO instructions are used and which PIO and SM are selected by default. Sorry, but the user will need to educate themselves about PIO if they wish to a PIO library in conjunction with others in their application.

When I started playing with the RP2040, there was no Arduino core available, so I used the Raspberry PI C SDK for the RP2040. When I wrote [Telemetrix for the Arduino Nano Connect](https://mryslab.github.io/telemetrix-nano-2040-wifi/), the Arduino core was available, and I used it instead of the RPi SDK. This library was in support of the Telemetrix effort. 

You may find it surprising that I used a KIM-1 6502 evaluation kit for my first consulting job. I designed and built the software for a fire alarm and security system for a City University Of New York campus. Those were fun times. I needed to modify some S100 bus memory boards to provide additional storage. I hand-assembled all the code because I couldn't afford to buy time on a 6502  assembler. By the time I was done, I knew all the 6502 opcodes without referring to the programming card.;-). BTW, my first programming experience was in school using Fortran with punch cards. There were no CRTs, microprocessors, or home computers at that time.

I think moving neoPixelFill() from the private to the public sector in the header file should make it accessible. There really is no magic to writing an Arduino library. The tricky part is getting the directory structure correct and having all the required administrative files if one wishes to use the Arduino library manager as a distribution manager. 

I will look at neoPixelFill, but I don't remember seeing the behavior you describe. Perhaps your device uses a slower clock than the devices I tested on.

**Comment by MrYsLab** [comment] 2022-03-22 15:37
I do not have time to test this at the moment, but if you have the time, could you please try this fix.
There is a .zip file attached.
[NeoPixelConnect.zip](https://github.com/MrYsLab/NeoPixelConnect/files/8325737/NeoPixelConnect.zip)

Download, but do not unzip. (You can unzip to see its contents, but it needs to be in the .zip form to install).

To install this library, you will first need to remove the old library. In the Arduino/libraries folder, remove the 
NeoPixelConnect folder and its contents.

To install this version of the library, in the Arduino IDE, select Sketch/Include Library/Add.ZIP library and select the file from above.

The library should now be installed.

The constructor has been changed to:

NeoPixelConnect(byte pinNumber, byte numberOfPixels, PIO pio, uint sm);

Please let me know if this solves the issue and I will publish to the Arduino library manager.

**Comment by marmilicious** [comment] 2022-03-22 22:39
> Well at this point I guess handing it over to Marc Miller [@marmilicious](https://github.com/marmilicious)

Hello @Gavin-Perry. I watch over the Reddit FastLED group, but I'm not the author of FastLED. That would be Mark Kriegsman.

**Comment by Gavin-Perry** [comment] 2022-03-23 18:20
Thanks for correcting it I had the wrong mark.

**Comment by MrYsLab** [comment] 2022-03-26 21:01
I had a few moments to test today, and I cannot make things work for anything other than pio0 and sm0. I do not have the time to chase down the cause. Therefore, I am leaving the library as is, and I am closing this issue. I have modified the readme.md file to indicate that the library uses pio0 and sm0.

**Comment by MrYsLab** [comment] 2022-03-29 19:25
While waiting for hardware parts to come in, I revisited this issue and resolved it with release 1.1.0

**Comment by MrYsLab** [comment] 2022-03-29 19:26
Closing this issue as resolved

**Closed as completed by MrYsLab** 2022-03-29 19:26 UTC
Labels: enhancement
