### ISSUE TITLE
Strange behaviour with NeoPixel Strips

### ISSUE THREAD

**Issue by KevinBDSL** [MrYsLab/NeoPixelConnect#8] opened 2024-10-07 11:08 UTC
I bought some 60LED strips from PiHut https://thepihut.com/products/flexible-rgb-led-strip-neopixel-ws2812-sk6812-compatible-60-led-meter?variant=40999774912707

I've got three of them so I'll eventually have 180 LEDs

I've connected one strip to a PICO-W with the data signal on pin 12 (GP1) (eventually these will be controlled by WIFI)

My problem is that when I address individual LEDs the LED i am addressing seems to shift by MAXIMUM_NUM_NEOPIXELS.

For example if I set MAXIMUM_NUM_NEOPIXELS to 20 and I then use neoPixelSetValue(LEDNo, RedVal, GreenVal, BlueVal, true); the 21st LED in the strip will be illuminated when LEDNo = 0
Here's my code
#define MAXIMUM_NUM_NEOPIXELS 20

#include <NeoPixelConnect.h>

// Create an instance of NeoPixelConnect and initialize it
// to use GPIO pin 1 as the control pin, for a string
// of 20 neopixels. Name the instance p

NeoPixelConnect p(1, MAXIMUM_NUM_NEOPIXELS, pio0, 0);

uint8_t ColourSequence[7][3] = {
    {255,0,0},
    {0,255,0},
    {0,0,255},
    {255,255,0},
    {255,0,255},
    {0,255,255},
    {255,255,255}
};
String ColourNames[7] = {
    "Red",
    "Green",
    "Blue",
    "Yellow",
    "Magenta",
    "Cyan",
    "White"
};

uint16_t CurrentColour = 0;
uint16_t CurrentLED = 0;
 
void setup()
{
    // put your setup code here, to run once:
    Serial.begin(115200);
    delay(2000);
    Serial.println("In setup");
}

void loop()
{
    p.neoPixelSetValue(CurrentLED, 0, 0, 0, true);

    CurrentLED++;
    if(CurrentLED >= MAXIMUM_NUM_NEOPIXELS)
    {
        CurrentLED = 0;
        CurrentColour++;
        Serial.println("");
        if(CurrentColour > 6 )
        {
            CurrentColour = 0;

        }
        Serial.print(ColourNames[CurrentColour]);
    }
    Serial.print(CurrentLED);
    Serial.print(",");
    p.neoPixelSetValue(CurrentLED, ColourSequence[CurrentColour][0],
                       ColourSequence[CurrentColour][1],
                       ColourSequence[CurrentColour][2], true);
    delay(500);
}

Both your fireworks and filldemo work as expected

I tried a couple of experiments

First I replaced p.neoPixelSetValue(CurrentLED, 0, 0, 0, true); with p.neoPixelClear(); at the beginning of the loop.

This had no effect.

Then I noticed that in both your demo programs you have a delay after every interaction so I added a delay(1); after the         p.neoPixelSetValue(CurrentLED, 0, 0, 0, true); and this fixed he problem.

Then I figured out that I could use     p.neoPixelSetValue(CurrentLED, 0, 0, 0, false); at the start of the loop as this would clear the memory for the LED in had just driven and I didn't need the delay.

It looks to me like in my original code the two sets of data (all 0's and my required data were being queued up and sent without a communications reset in between (hence my real data being shifted by the number of LEDs I'd defined.  I'm not sure if this is a function of the PIO code or the code that queues up the data via DMA.

**Comment by MrYsLab** [comment] 2024-10-07 14:11
Thanks for the detailed report. I do not have an LED strip larger than eight neopixels and therefore cannot test beyond that, but a user resolved an earlier issue and tested it with 300 pixels, and their [pull request](https://github.com/MrYsLab/NeoPixelConnect/pull/5) was incorporated into the code.

You mentioned that you tested my examples successfully. I assume you modified the PIN used in the example code for the fireworks example. Did you also modify [MAXIMUM_NUM_PIXELS](https://github.com/MrYsLab/NeoPixelConnect/blob/5e8aa3c5f9d8b3324413013cd9a9265666e490b0/examples/fireworks/fireworks.ino#L18) for a number greater than 8, and did that work as well?

**Comment by KevinBDSL** [comment] 2024-10-07 14:36
Hi
Yes I modified your examples to use my chosen pin and set MAXIMUM_NUM_NEOPIXELS to 60 they still worked.

I think the issue was that I had AutoSHow set to true on all my calls to functions to turn on or off pixels.  If you run two consecutive calls without a delay then both sets of data get queued up to the PIO and are sent consecutively without a reset in between.

If you have only got 8 LEDs try the following in your fill_demo
Set MAXIMUM_NUM_NEOPIXELS to 4
the  modify the loop as follows
void loop(){

    // set all LEDs to red, then green, and then blue
   p.neoPixelClear(true);  // first clear what is there
 
    p.neoPixelFill(255, 0, 0, true);  // red
    delay(1000);

    p.neoPixelClear(true);
    p.neoPixelFill(0, 255, 0, true);  // green
    delay(1000);

    p.neoPixelClear(true);
    p.neoPixelFill(0, 0, 255, true);  // blue
    delay(1000);
}

I suspect you will see that the last four LEDs light up rather than the first four.

I think the issue is that if you set two lots of values with Autoshow set to true with no delay in between you don't get a reset pulse (low for 200uS) on the serial link before the second set of data starts transmitting so the LEDs interpret the data as one continuous steam rather than two separate ones.  I'm guessing that the pin is low when there is no data to send.

The trick therefore is to setup all your pixels as you want them with Autoshow = false then run neoPixelShow() when they are all set up

If you set    MAXIMUM_NUM_NEOPIXELS to 8 and then run the above code nothing will happen and you'll think (as I did) that something is wrong with the LEDs

Kevin

**Comment by MrYsLab** [comment] 2024-10-07 16:28
Thanks again for the info. I added a note to the bottom of the Readme.md page that states:

A Programming Note:
Neopixel timing is critical. If your sketch is crafted in a way that interferes with the timing, resulting in an unexpected visual result, you may wish to call neoPixelSetValue using the default value for the autoshow parameter set to false and then calling neoPixelShow after all Neopixel values have been set.

Placing a small delay at the end of the sketch loop may also solve the issue.

I hope this helps to solve the issue. I will close the issue, but you may reply, and I will see the reply even though the issue is closed.

Thanks again for all the detailed work you have done.

**Closed as completed** 2024-10-07 16:29 UTC

**Comment by KevinBDSL** [comment] 2024-10-08 10:13
Thanks Alan
That will hopefully help people if/when they fall down the same hole I did.

When I have the time to learn the PIO language I might look at adding a 100uS reset pulse before starting to send the data.  Another library I use (Pico-DMX) does something similar as the DMX protocol requires a serial break before starting to send data.

Kevin
